version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: 'sales_db'
  MYSQL_PASSWORD: 'admin'
  MYSQL_USER: 'root'

services:
  mysql-development:
    image: mysql:latest
    container_name: mysqlcontainer
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: 'admin'

  back-end:
    build:
      dockerfile: Dockerfile
      context: "./back-end"
    depends_on:
      - mysql-development
    volumes:
      - /app/node_modules
      - ./back-end:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-development
    ports:
      - "8000:8000"

  front-end:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./front-end:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "7000:8080"
    depends_on:
      - mysql-development
    environment:
      ADMINER_DEFAULT_SERVER: mysql-development

networks:
  internalnet:
    driver: bridge
