version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: sales_db
  MYSQL_PASSWORD: admin

services:
  mysql_db:
    image: mysql
    container_name: mysqlcontainer
    restart: unless-stopped
    cap_add:
      - SYS_NICE
#    volumes:
#      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
    networks:
      - internalnet

#  nginx:
#    depends_on:
#      - back-end
#      #- front-end
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - "3050:80"

  back-end:
    build:
      dockerfile: Dockerfile
      context: "./back-end"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./back-end:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - "8000:8000"

  front-end:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./front-end:/app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "7000:8080"
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db

networks:
  internalnet:
    driver: bridge
